[build]
builder = "NIXPACKS"
buildCommand = "cd nodejs_space && yarn install && yarn prisma generate && yarn build"

[deploy]
startCommand = "cd nodejs_space && yarn start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
